pipeline{
    agent any 
    environment{
        DOCKERHUB_CREDENTIAL=credentials('docker-hub');
    }
    stages{
        stage('Docker LOGIN'){
            steps{
                sh 'echo "$DOCKERHUB_CREDENTIAL_USR" | docker login -u "$DOCKERHUB_CREDENTIAL_USR" --password-stdin'            }
        }
        
        stage('Docker build and push'){
            steps{
                sh """
                cd simple-projects2
                ansible-playbook ansible-playbook.yml
                """
            }
            
        }
    }
}
